[".fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf"
    refreshPeriod = "168h"

[".zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto"
    refreshPeriod = "168h"

[".spacemacs.d"]
    type = "git-repo"
    url = "https://github.com/syl20bnr/spacemacs"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
