name: MacOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Install chezomi
        run: sh -c "$(curl -fsLS get.chezmoi.io)"
      
      - run: |
          src_dir="/Users/runner/work/dotfiles-chezmoi/dotfiles-chezmoi"
          dst_dir="/Users/runner/.local/share/chezmoi"
          ln -sfnv "${src_dir}" "${dst_dir}"

      - name: run chezmoi init
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          SYSTEM: system
        run: printf '${EMAIL_ADDRESS}\n${SYSTEM}'| ./bin/chezmoi --no-tty init
